[2022-08-07 15:07:36,947] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: load_ad_data.load_briefing_data manual__2022-08-07T11:51:07.834855+00:00 [queued]>
[2022-08-07 15:07:36,999] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: load_ad_data.load_briefing_data manual__2022-08-07T11:51:07.834855+00:00 [queued]>
[2022-08-07 15:07:36,999] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-07 15:07:36,999] {taskinstance.py:1377} INFO - Starting attempt 6 of 6
[2022-08-07 15:07:36,999] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-07 15:07:37,008] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): load_briefing_data> on 2022-08-07 11:51:07.834855+00:00
[2022-08-07 15:07:37,011] {standard_task_runner.py:52} INFO - Started process 103038 to run task
[2022-08-07 15:07:37,012] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'load_ad_data', 'load_briefing_data', 'manual__2022-08-07T11:51:07.834855+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_raw_data_loader.py', '--cfg-path', '/tmp/tmp4cf4hfwm', '--error-file', '/tmp/tmpod0u47cl']
[2022-08-07 15:07:37,013] {standard_task_runner.py:80} INFO - Job 190: Subtask load_briefing_data
[2022-08-07 15:07:37,024] {logging_mixin.py:115} WARNING - /home/hp/miniconda3/envs/checker/lib/python3.8/site-packages/airflow/configuration.py:532 DeprecationWarning: The sql_engine_encoding option in [core] has been moved to the sql_engine_encoding option in [database] - the old setting has been used, but please update your config.
[2022-08-07 15:07:37,039] {task_command.py:371} INFO - Running <TaskInstance: load_ad_data.load_briefing_data manual__2022-08-07T11:51:07.834855+00:00 [running]> on host hp-HP-Pavilion-Laptop-15-eg0xxx
[2022-08-07 15:07:37,068] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=tesfaye
AIRFLOW_CTX_DAG_ID=load_ad_data
AIRFLOW_CTX_TASK_ID=load_briefing_data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-07T11:51:07.834855+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-07T11:51:07.834855+00:00
[2022-08-07 15:07:37,075] {base.py:68} INFO - Using connection ID 'postgres_connection' for task execution.
[2022-08-07 15:07:37,082] {sql.py:255} INFO - Running statement: COPY briefing FROM './data/briefing.csv' WITH DELIMITER AS ';' NULL AS '\null' CSV HEADER;, parameters: None
[2022-08-07 15:07:37,082] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hp/miniconda3/envs/checker/lib/python3.8/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/hp/miniconda3/envs/checker/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 234, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/hp/miniconda3/envs/checker/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 260, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open file "./data/briefing.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2022-08-07 15:07:37,084] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=load_ad_data, task_id=load_briefing_data, execution_date=20220807T115107, start_date=20220807T120736, end_date=20220807T120737
[2022-08-07 15:07:37,092] {standard_task_runner.py:92} ERROR - Failed to execute job 190 for task load_briefing_data (could not open file "./data/briefing.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 103038)
[2022-08-07 15:07:37,104] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-07 15:07:37,121] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
